### ISSUE TITLE
building rom

### ISSUE THREAD

**Issue by pswapnil571** [manjotsidhu/android_device_micromax_a106#1]
plz build this los15 rom for unite 2 and uploading any sites............

**Comment by manjotsidhu** [comment]
I would like to but I left android development so RIP ... Maybe @imranpopz can help you

**Comment by imranpopz** [comment]
Lol @manjotsidhu

**Comment by pswapnil571** [comment]
> Lol @manjotsidhu

plz bro build this rom for unite 2

**Comment by manjotsidhu** [comment]
CIP
